import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated by docusaurus-plugin-openapi-docs from ../apis/openapi.yaml.
// Regenerate with: npm run gen-api-docs product-master
import apiSidebar from './docs/api-reference/rest/sidebar';

/**
 * Top-level categories follow the shared warehouse-systems documentation
 * layout: Overview, Domain-Driven Design, API Reference, Ecosystem and
 * Architecture Decision Records. The ADR files live in docs/adr/ and are served
 * by the second docs plugin instance (id: 'adr'), hence the plain links.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      link: {type: 'doc', id: 'overview/context'},
      items: [
        'overview/aggregates',
        'overview/physical-profile',
        'overview/runtime',
      ],
    },
    {
      type: 'category',
      label: 'Domain-Driven Design',
      link: {type: 'doc', id: 'ddd/ubiquitous-language'},
      items: [
        'ddd/use-cases',
        {
          type: 'category',
          label: 'DDD artifacts (ddd-crew)',
          link: {type: 'doc', id: 'ddd/ddd-artifacts'},
          items: [
            'ddd/core-domain-chart',
            'ddd/bounded-context-canvas',
            'ddd/context-map',
            'ddd/aggregate-design-canvas',
            'ddd/domain-message-flow',
            'ddd/eventstorming',
            'ddd/class-diagram',
            'ddd/entity-relationship',
            'ddd/sequence-diagrams',
            'ddd/domain-events',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'doc', id: 'api-reference/overview'},
      items: [...apiSidebar, 'api-reference/events'],
    },
    {
      type: 'category',
      label: 'Ecosystem',
      link: {type: 'doc', id: 'ecosystem/downstream-consumers'},
      items: ['ecosystem/upstream-contracts'],
    },
    {
      type: 'category',
      label: 'Architecture Decision Records',
      items: [
        {
          type: 'link',
          label: '0001 Bounded context',
          href: '/docs/adr/0001-product-master-bounded-context',
        },
        {
          type: 'link',
          label: '0002 Physical profile, declared vs measured',
          href: '/docs/adr/0002-physical-profile-declared-vs-measured',
        },
        {
          type: 'link',
          label: '0003 Migration from inventory-storage',
          href: '/docs/adr/0003-migration-from-inventory-storage',
        },
        {
          type: 'link',
          label: '0004 CloudEvents envelope and type catalogue',
          href: '/docs/adr/0004-cloudevents-envelope-and-type-catalogue',
        },
      ],
    },
  ],
};

export default sidebars;
