{{- if .Values.mcp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "product-master.mcpFullname" . }}
  labels:
    {{- include "product-master.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp
spec:
  type: {{ .Values.mcp.service.type }}
  ports:
    - port: {{ .Values.mcp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "product-master.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mcp
{{- end }}
